config/routes.rb
Rails.application.routes.draw do
  get "signup" => "users#new"
  resources :users
  post '/home/guest_sign_in', to: 'home#guest_sign_in'
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"
  get "users/:id/likes" => "users#likes"
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  devise_for :users
  resources :posts
  root "home#index"
  get "about" => "home#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#  user_id    :integer
#
class Like < ApplicationRecord
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Post < ApplicationRecord
    validates :content, {presence: true, length: {maximum: 100}}
    validates :user_id, {presence: true}
    mount_uploader :file, AudioUploader

    belongs_to :user

    def user
        return User.find_by(id: self.user_id)
    end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  name                   :string(255)
#  password               :string(255)
#  password_confirmation  :string(255)
#  password_digest        :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  # validates :password, {presence: true}
  has_secure_password
  # devise :database_authenticatable
  has_many :posts, dependent: :destroy   
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      image_name = "999"
    end
  end

  # def posts
  #   return Post.where(user_id: self.id)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
      if params[:action] == "guest_sign_in"
        session[:user_id] = 1
      end
      @current_user = User.find_by(id: session[:user_id])
    end

    def authenticate_user
      if @current_user == nil
        flash[:notice] = "ログインが必要です"
        redirect_to("/login")
      end
    end

    def forbid_login_user
      if @current_user
        flash[:notice] = "すでにログインしています"
        redirect_to posts_path
      end
    end

    # def after_sign_in_path_for(resource)
    #   users_path(resource)
    # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :forbid_login_user, {only: [:top]}

  def top
  end

  def about
  end

  def index
  end

  def guest_sign_in
    user = User.guest
    redirect_to posts_path, notice: "#{ current_user.name }でログインしました"
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user
    
    def create
      @like = Like.new(user_id: @current_user.id, post_id: params[:post_id])
      @like.save
      redirect_to("/posts/#{params[:post_id]}")
    end

    def destroy
      @like = Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
      @like.destroy
      redirect_to("/posts/#{params[:post_id]}")    
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
    @likes_count = Like.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      content: params[:post][:content],
      user_id: @current_user.id,
      file: params[:post][:file]
    )
    if @post.save
      flash[:notice] = "投稿を作成しました"
      redirect_to posts_path
    else
      render new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました"
      redirect_to posts_path
    else
      render("posts/edit")
    end  
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to posts_path
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to posts_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name], 
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation],
      image_name: "default_user.jpg"
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
      flash[:notice] = "ユーザー登録が完了しました"
    else
      flash[:error] = "作成に失敗しました"
      render ("users/new")
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update            
    @user = User.find_by(id: params[:id])            
    @user.name = params[:name]            
    @user.email = params[:email]
    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end            
    if @user.save                        
      redirect_to("/users/#{@user.id}")
      flash[:notice] = "ユーザー情報を編集しました"            
    else            
      render("users/edit")        
    end            
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to posts_path
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("users/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about-main">
  <h2>VoiceLifeとは</h2>
  <p>
    SNSサービスです。
    近況やつぶやきを声を投稿し、楽しくコミュニケーションできます。
  </p>
</div>

app/views/home/index.html.erb
<!--<div class="main posts-new">
  <div class="container">
    <%= button_to 'ゲストログイン（閲覧用）', home_guest_sign_in_path, method: :post %>
  </div>
</div>-->

<div class="main top-main">
  <div class="top-message">
    <h2>あなたの声を世界に届けよう</h2>
  </div>
</div>

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>あなたの声を世界に届けよう</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoiceLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class="a">
      <header>
          <div class="header-logo">
            <% if @current_user %>
              <%= link_to("VoiceLife",  posts_path) %>
            <% else %>
              <%= link_to("VoiceLife", "/") %>
            <% end %>    
          </div>
          <img src="top-icon.png" width="30" height="30">
          <ul class="header-menus">
            <% if @current_user %>
              <li class="user-image">
                <img src="<%= "/user_images/#{@current_user.image_name}" %>">
              </li>
              <li>
                <%= link_to(@current_user.name, user_path(@current_user)) %>
              </li>
              <li>
                <%= link_to("投稿一覧", posts_path) %>
              </li>
              <li>
                <%= link_to("新規投稿", new_post_path) %>
              </li>
              <li>
                <%= link_to("ユーザー一覧", users_path) %>
              </li>
              <li>
                <%= form_tag "/logout", { method: :post } do %>
                <%= submit_tag 'ログアウト' %>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to("VoiceLifeとは","/about") %>
              </li>
              <li>
                <%= link_to("新規登録","/signup") %>
              </li>
              <li>
                <%= link_to("ログイン", "/login") %>
              </li>
              <li>
                <%= button_to 'ゲストログイン（閲覧用）', home_guest_sign_in_path, {method: :post, class: "guest-button"} %>
              </li>
            <% end %>         
          </ul>
      </header>
    </div>  
  

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>   

    <%= yield %>

    <footer>
    </footer>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
    <%= form_tag(post_path(@post), method: :put ) do %>
    <div class="form">
      <div class="form-body">
        <% @post.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <textarea name="content"><%= @post.content %></textarea>
        <input type="submit" value="保存">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>  
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
    <div class="form">
      <% @post.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
      <%= form_for @post do |f| %>
        <p style="background-color:#f5f8fa";>コンテンツ</p>
        <%= f.text_area :content %>
        <p style="background-color:#f5f8fa";>ファイル</p>
        <%= f.file_field :file , :size => 140 %>
        <%= f.submit "送信" %>
      <% end %>
    </div>  
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <div class="post-user-name">
        <img src="<%= "/user_images/#{@user.image_name}" %>">
        <%= link_to(@user.name, user_path(@user)) %>
      </div>  
      <p>
        <%= @post.content %>
      </p>
      <% if @post.file.present? %> 
        <%= audio_tag @post.file_url, :controls => true %>
      <% end %>  
      <div class="post-time">
        <%= @post.created_at %>
      </div>
      <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
        <%= form_tag "/likes/#{@post.id}/destroy", { method: :post } do %>
          <%= button_tag type: :submit, style: "border-style: none; background: none;" do %>
            <span class="fa fa-heart liked-btn"></span>
          <% end %>
        <% end %>
      <% else %>
        <%= form_tag "/likes/#{@post.id}/create", { method: :post } do %>
          <%= button_tag type: :submit, style: "border-style: none; background: none;" do %>
            <span class="fa fa-heart unliked-btn"></span>
          <% end %>
        <% end %>
      <% end %>
      <%= @likes_count %>    
      <% if @post.user_id == @current_user.id %>
        <div class="post-menus">
          <%= link_to("編集", "/posts/#{@post.id}/edit") %>
          <%= form_tag post_path(@post), method: :delete do %>
          <%= submit_tag '削除' %>
          <% end %>
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">ユーザー情報の編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>            
          <div class="form-error">            
          <%= message %>            
          </div>            
        <% end %>
      <%= form_tag user_path(@user), method: :put, multipart: true do %>
        <p>ユーザー名</p>
        <input name="name" value= "<%= @user.name %>">
        <p>画像</p>
        <input name="image" type="file">
        <p>メールアドレス</p>
        <input name="email" value="<%= @user.email %>">
        <input type="submit" value="保存">
      <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <img src="<%= "/user_images/#{user.image_name}" %>">
        </div>
        <div class="user-right">
          <%= link_to(user.name, "/users/#{user.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    <% @likes.each do |like| %>
      <% post = Post.find_by(id: like.post_id) %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
          <% if @error_message %>
            <div class="form-error">
              <%= @error_message %>
            </div>
          <% end %>
          <%= form_tag("/login") do %>
            <p style="color: black">メールアドレス</p>
            <input name="email" value="<%= @email %>">
            <p style="color: black">パスワード</p>
            <input type="password" name="password" value="<%= @password %>">
            <input type="submit" value="ログイン">
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
        <%= form_tag users_path do %>
          <p>ユーザー名</p>
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <input name="email" value="<%= @user.email %>">            
          <p>パスワード</p>
          <input type="password" name="password" value="<%= @user.password %>">
          <p>パスワード確認</p>
          <input type="password" name="password_confirmation" value="<%= @user.password_confirmation %>">
          <input type="submit" value="新規登録">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    <% @user.posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>